#ifndef VERSION_H
#define VERSION_H

#define STRINGIFY_INTERNAL(x) #x
#define STRINGIFY(x) STRINGIFY_INTERNAL(x)

#define VERSION 2.0.2
const char* const VERSION_STR = STRINGIFY(VERSION);

#define VERSION_MAJOR 2
const char* const VERSION_MAJOR_STR = STRINGIFY(VERSION_MAJOR);
#define VERSION_MINOR 0
const char* const VERSION_MINOR_STR = STRINGIFY(VERSION_MINOR);
#define VERSION_RELEASE 2
const char* const VERSION_RELEASE_STR = STRINGIFY(VERSION_RELEASE);

#define REVISION 4d5174b9736ff54892f42a3a562ae1ca4273c86e
const char* const REVISION_STR = STRINGIFY(REVISION);

#define BUILT_TIME March 31 2018 15:06:30 +0800
const char* const BUILT_TIME_STR = STRINGIFY(BUILT_TIME);

#undef REVISION
#undef BUILT_TIME
#undef STRINGIFY_INTERNAL
#undef STRINGIFY

#endif